spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rent_car?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: admin

  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
  messages:
    encoding: UTF-8
    basename: messages

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 3MB

  mail:
    rentCar: ${EMAIL:}
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL:@gmail.com}
    password: ${EMAIL_PASSWORD:}

#  remember:
#    key: ${}


#cloudinary:
#  name: ${CLOUDINARY_NAME:}
#  api-key: ${CLOUDINARY_API_KEY:}
#  api-secret: ${CLOUDINARY_API_SECRET:}

#logging:
#  level:
#    org:
#      springframework:
#       security: DEBUG
